config/routes.rb
Rails.application.routes.draw do

  root "sessions#index"
  
  get "password_resets/new"
  post "users/set_list_item_orderings"
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "logged_in" => "sessions#index", :as => "logged_in"
  
  resources :users
  resources :sessions
  resources :password_resets
  resources :list_items

end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  before_create { generate_token(:auth_token) }

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  def new
    @listitem = ListItem.new
  end
  
  def create
    @listitem = ListItem.new(list_item_params)
    
    itemsWithSameLabel = ListItem.find_by(user: current_user.id, label: @listitem.label)
    if !itemsWithSameLabel
      #create and save a new list item
      @listitem.user = current_user.id
      @listitem.index = ListItem.where(user: current_user.id).length
      
      if @listitem.save
        @listitem = ListItem.new
        @listitems = ListItem.where(user: current_user.id).order(:index)
        redirect_to logged_in_path
      else
        @listitem = ListItem.new
        @listitems = ListItem.where(user: current_user.id).order(:index)
        redirect_to logged_in_path
      end
    else
      #item already exists with same label
      @listitem = ListItem.new
      @listitems = ListItem.where(user: current_user.id).order(:index)
      redirect_to logged_in_path
    end
  end
  
  def list_item_params
    params.require(:list_item).permit(:label,:user,:index)
  end
  
  def destroy
    #get the list item to remove
    listItemToRemove = ListItem.find(params[:id])
    
    #for all items with an index greater than that of the item being removed,
    #we want to decrease its index accordingly in order to maintain the ordering
    #of the list items
    listItemToRemoveIndex = listItemToRemove.index
    listitems = ListItem.where(user: current_user.id)
    for listItem in listitems
      if listItem.index > listItemToRemoveIndex
        listItem.index -= 1
        listItem.save
      end
    end
    
    #destroy the item
    listItemToRemove.destroy
    
    #update the list items value with the remaining list items
    @listitems = ListItem.where(user: current_user.id).order(:index)
    
    redirect_to logged_in_path
    
    #render :partial => 'list_items/listContainer', :layout => false, :object => @listitems
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user
      user.send_password_reset
      redirect_to root_url, :notice => "Email sent with password reset instructions."
    else
      render :new
    end
  end
  
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end
  
  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(params[:user].permit(:password, :password_confirmation, :password_reset_token))
      redirect_to root_url, :notice => "Password has been reset!"
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def index
    if !current_user
      redirect_to log_in_path
    else
      @listitem = ListItem.new
      @listitems = ListItem.where(user: current_user.id).order(:index)
    end
  end
  
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to logged_in_path
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to log_in_path, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    if current_user
      redirect_to logged_in_path
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to log_in_path
    else
      render "new"
    end
  end
  
  def set_list_item_orderings
    
    listitems = ListItem.where(user: current_user.id)
    for listItem in listitems
      listItem.index = params[listItem.label]
      listItem.save
    end
    
    @listitems = ListItem.where(user: current_user.id).order(:index)
    
    redirect_to logged_in_path
  end
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_item_helper.rb
module ListItemHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo List</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_tag "auth_token = '#{form_authenticity_token}'" %>
  <%= csrf_meta_tags %>
  
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 

	<title>lists</title>
	<meta name="description" content="Lists">

	<link href='https://fonts.googleapis.com/css?family=Archivo+Narrow&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  
</head>
<body bgcolor="#5cbf94">

<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/list_items/_listContainer.html.erb
<ul class="sortable list" id="listContainer">
	<% if @listitems %>
		<% for item in @listitems.each do [item] %>
		    <li id="todoListElement">
		    	<div id="handle">
		    		<img src="<%= image_path('handle.png') %>" draggable=false>
		    	</div>
		    	<div id="itemText">
		    		<%= item.label %>
		    	</div>
		    	<div id="deleteElement">
		    		<%= link_to image_tag("delete.png"), item, :method => :delete %>
		    	</div>
		    </li>
		<% end %>
	<% end %>
</ul>

app/views/list_items/new.html.erb
<h1>ListItem#new</h1>
<p>Find me in app/views/list_item/new.html.erb</p>

app/views/password_resets/edit.html.erb
<div class="centerPanel">
  <%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <br>
    <div><%= f.submit "Update Password", :class => 'greenButton' %></div>
  <% end %>
</div>

app/views/password_resets/new.html.erb
<div class="centerPanel">
  <%= form_tag password_resets_path, :method => :post do %>
    <div class="field">
      <%= label_tag :email %>
      <%= text_field_tag :email, params[:email] %>
    </div>
    <br>
    <div><%= submit_tag "Reset Password", :class => 'greenButton' %></div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="centerPanel">
  <h1>Sign Up</h1>
  
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
    <p><%= f.submit "Sign up", :class => 'greenButton'%></p>
  <% end %>
</div>